version: 2.1

description: |
  Deploy applications to Convox
  You must set your Convox deploy key as a project environment variable CONVOX_PASSWORD

display:
  home_url: https://convox.com
  source_url: https://github.com/convox/circleci-orb

examples:
  deploy:
    description: Deploy your application to Convox using the jobs from this orb
    usage:
      version: 2.1
      orbs:
        convox: convox/orb@x.y
      workflows:
        deploy:
          jobs:
            - checkout
            - convox/deploy:
                rack: production
                app: example

  test_and_deploy:
    description: Customize your workflow using the commands from this orb
    usage:
      version: 2.1
      orbs:
        convox: convox/orb@x.y
      workflows:
        deploy:
          jobs:
            - deploy
      jobs:
        deploy:
          executor: convox/cli
          steps:
            - checkout
            - run: make test
            - convox/deploy:
                rack: production
                app: example

executors:
  cli:
    description: Convox CLI
    docker:
      - image: convox/circleci
    working_directory: ~/convox

commands:
  deploy:
    parameters:
      app:
        description: Application Name
        type: string
        default: "$CIRCLE_PROJECT_REPONAME"
      rack:
        description: Rack Name
        type: string
        default: "$CONVOX_RACK"
      host:
        description: Console Hostname
        type: string
        default: "console.convox.com"
    steps:
      - run: mkdir -p workspace
      - run:
          name: Deploy Application
          environment:
            CONVOX_HOST: << parameters.host >>
            CONVOX_RACK: << parameters.rack >>
          command: convox deploy --app << parameters.app >>

jobs:
  deploy:
    parameters:
      app:
        description: Application Name
        type: string
        default: "$CIRCLE_PROJECT_REPONAME"
      rack:
        description: Rack Name
        type: string
        default: "$CONVOX_RACK"
      host:
        description: Console Hostname
        type: string
        default: "console.convox.com"
    executor: cli
    steps:
      - checkout
      - deploy:
          app: << parameters.app >>
          rack: << parameters.rack >>
          host: << parameters.host >>
